#ifndef TNTCTL_TEXT_H
#define TNTCTL_TEXT_H

#include "common.h"

typedef enum {
    TNTCTL_TEXT_USAGE,
    TNTCTL_TEXT_INVALID_PORT,
    TNTCTL_TEXT_INVALID_LOGIN,
    TNTCTL_TEXT_INVALID_HOST_KEY_MODE,
    TNTCTL_TEXT_INVALID_KNOWN_HOSTS,
    TNTCTL_TEXT_UNKNOWN_OPTION_FORMAT,
    TNTCTL_TEXT_MISSING_HOST,
    TNTCTL_TEXT_INVALID_HOST,
    TNTCTL_TEXT_LOGIN_HOST_CONFLICT,
    TNTCTL_TEXT_UNKNOWN_COMMAND,
    TNTCTL_TEXT_INVALID_REMOTE_COMMAND,
    TNTCTL_TEXT_DESTINATION_TOO_LONG,
    TNTCTL_TEXT_INVALID_DESTINATION,
    TNTCTL_TEXT_OUT_OF_MEMORY,
    TNTCTL_TEXT_HOST_KEY_OPTION_TOO_LONG,
    TNTCTL_TEXT_KNOWN_HOSTS_OPTION_TOO_LONG,
    TNTCTL_TEXT_COUNT
} tntctl_text_id_t;

const char *tntctl_text(ui_lang_t lang, tntctl_text_id_t id);

#endif /* TNTCTL_TEXT_H */
