#include "help_text.h"

const char *help_text_full(help_lang_t lang) {
    if (lang == LANG_EN) {
        return "TNT KEY REFERENCE\n"
               "\n"
               "OPERATING MODES:\n"
               "  INSERT  - Type and send messages (default)\n"
               "  NORMAL  - Browse message history\n"
               "  COMMAND - Execute commands\n"
               "\n"
               "INSERT MODE KEYS:\n"
               "  ESC        - Enter NORMAL mode\n"
               "  Enter      - Send message\n"
               "  Backspace  - Delete character\n"
               "  Ctrl+W     - Delete last word\n"
               "  Ctrl+U     - Delete line\n"
               "  Ctrl+C     - Enter NORMAL mode\n"
               "\n"
               "NORMAL MODE KEYS:\n"
               "  Opens at latest messages\n"
               "  Follows latest until you scroll up\n"
               "  i          - Return to INSERT mode\n"
               "  :          - Enter COMMAND mode\n"
               "  j/k        - Scroll down/up one line\n"
               "  Ctrl+D/U   - Scroll half page down/up\n"
               "  Ctrl+F/B   - Scroll full page down/up\n"
               "  PgDn/PgUp  - Scroll full page down/up\n"
               "  End/Home   - Jump to bottom/top\n"
               "  g/G        - Jump to top/bottom\n"
               "  ?          - Show full key reference\n"
               "  Ctrl+C     - Exit chat\n"
               "\n"
               "AVAILABLE COMMANDS:\n"
               "  :list, :users        - Show online users\n"
               "  :nick <name>         - Change nickname\n"
               "  :msg <user> <text>   - Whisper to user\n"
               "  :w <user> <text>     - Short alias for :msg\n"
               "  :inbox               - Show whispers\n"
               "  :last [N]            - Show last N messages (max 50)\n"
               "  :search <keyword>    - Search message history\n"
               "  :mute-joins          - Toggle join/leave notices\n"
               "  :help                - Show concise manual\n"
               "  :lang <en|zh>        - Switch UI language\n"
               "  :clear               - Clear command output\n"
               "  :q, :quit, :exit     - Disconnect\n"
               "\n"
               "SPECIAL MESSAGES:\n"
               "  /me <action>      - Send action (e.g. /me waves)\n"
               "  @username         - Mention user (bell + highlight)\n"
               "\n"
               "HELP SCREEN KEYS:\n"
               "  q, ESC     - Close help\n"
               "  j/k        - Scroll down/up\n"
               "  Ctrl+D/U   - Scroll half page down/up\n"
               "  Ctrl+F/B   - Scroll full page down/up\n"
               "  g/G        - Jump to top/bottom\n"
               "  e/z        - Switch English/Chinese\n";
    }

    return "TNT 按键参考\n"
           "\n"
           "操作模式:\n"
           "  INSERT  - 输入和发送消息(默认)\n"
           "  NORMAL  - 浏览消息历史\n"
           "  COMMAND - 执行命令\n"
           "\n"
           "INSERT 模式按键:\n"
           "  ESC        - 进入 NORMAL 模式\n"
           "  Enter      - 发送消息\n"
           "  Backspace  - 删除字符\n"
           "  Ctrl+W     - 删除上个单词\n"
           "  Ctrl+U     - 删除整行\n"
           "  Ctrl+C     - 进入 NORMAL 模式\n"
           "\n"
           "NORMAL 模式按键:\n"
           "  默认停在最新消息\n"
           "  未向上翻阅时自动跟随最新消息\n"
           "  i          - 返回 INSERT 模式\n"
           "  :          - 进入 COMMAND 模式\n"
           "  j/k        - 向下/上滚动一行\n"
           "  Ctrl+D/U   - 向下/上滚动半页\n"
           "  Ctrl+F/B   - 向下/上滚动整页\n"
           "  PgDn/PgUp  - 向下/上滚动整页\n"
           "  End/Home   - 跳到底部/顶部\n"
           "  g/G        - 跳到顶部/底部\n"
           "  ?          - 显示完整按键参考\n"
           "  Ctrl+C     - 退出聊天\n"
           "\n"
           "可用命令:\n"
           "  :list, :users        - 显示在线用户\n"
           "  :nick <名字>         - 更改昵称\n"
           "  :msg <用户> <文本>   - 私聊\n"
           "  :w <用户> <文本>     - :msg 的简写\n"
           "  :inbox               - 查看私聊\n"
           "  :last [N]            - 显示最后 N 条消息(最多50)\n"
           "  :search <关键词>     - 搜索消息历史\n"
           "  :mute-joins          - 切换加入/离开提示\n"
           "  :help                - 显示简明手册\n"
           "  :lang <en|zh>        - 切换界面语言\n"
           "  :clear               - 清空命令输出\n"
           "  :q, :quit, :exit     - 断开连接\n"
           "\n"
           "特殊消息:\n"
           "  /me <动作>        - 发送动作 (如 /me 挥手)\n"
           "  @用户名           - 提及用户 (响铃+高亮)\n"
           "\n"
           "帮助界面按键:\n"
           "  q, ESC     - 关闭帮助\n"
           "  j/k        - 向下/上滚动\n"
           "  Ctrl+D/U   - 向下/上滚动半页\n"
           "  Ctrl+F/B   - 向下/上滚动整页\n"
           "  g/G        - 跳到顶部/底部\n"
           "  e/z        - 切换英文/中文\n";
}
