#include "manual_text.h"

const char *manual_text_interactive(help_lang_t lang) {
    if (lang == LANG_ZH) {
        return "\033[1;36mTNT(1) 帮助\033[0m\n"
               "\n"
               "\033[1;37m名称\033[0m\n"
               "  TNT - SSH 终端聊天室\n"
               "\n"
               "\033[1;37m快速开始\033[0m\n"
               "  直接输入消息，Enter 发送\n"
               "  Esc 进入 NORMAL 浏览历史；G 回到最新；i 继续输入\n"
               "  : 输入命令；q 或 Esc 关闭输出面板\n"
               "\n"
               "\033[1;37m命令\033[0m\n"
               "  :users                 在线用户\n"
               "  :last [N]              最近消息，默认 10，最多 50\n"
               "  :search <关键词>       搜索历史\n"
               "  :msg <用户> <文本>     私聊\n"
               "  :inbox                 私聊收件箱\n"
               "  :nick <名字>           修改昵称\n"
               "  :mute-joins            静音/开启进出提示\n"
               "  :clear                 清空命令输出\n"
               "  :q                     断开连接\n"
               "\n"
               "\033[1;37m语言\033[0m\n"
               "  :lang                  显示当前语言\n"
               "  :lang zh               切换中文\n"
               "  :lang en               切换英文\n"
               "\n"
               "\033[1;37m参见\033[0m\n"
               "  ?                      完整按键参考\n";
    }

    return "\033[1;36mTNT(1) help\033[0m\n"
           "\n"
           "\033[1;37mName\033[0m\n"
           "  TNT - SSH terminal chat room\n"
           "\n"
           "\033[1;37mQuick start\033[0m\n"
           "  Type a message and press Enter to send\n"
           "  Esc enters NORMAL history browsing; G jumps latest; i types again\n"
           "  : enters COMMAND mode; q or Esc closes output panels\n"
           "\n"
           "\033[1;37mCommands\033[0m\n"
           "  :users                 show online users\n"
           "  :last [N]              show recent messages, default 10, max 50\n"
           "  :search <keyword>      search history\n"
           "  :msg <user> <text>     whisper privately\n"
           "  :inbox                 show whispers\n"
           "  :nick <name>           change nickname\n"
           "  :mute-joins            toggle join/leave notices\n"
           "  :clear                 clear command output\n"
           "  :q                     disconnect\n"
           "\n"
           "\033[1;37mLanguage\033[0m\n"
           "  :lang                  show current language\n"
           "  :lang en               switch to English\n"
           "  :lang zh               switch to Chinese\n"
           "\n"
           "\033[1;37mSee also\033[0m\n"
           "  ?                      full key reference\n";
}
